sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23

before_install:
- chmod +x gradlew

script:
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"

after_success:
- sh set_tags.sh

notifications:
  email: true

deploy:
  provider: releases
  api_key:
    secure: sETGZo1UfAkNxlbA2he2/pelw1ao/KrK7OXZmDZu/p7MBnE9dxlNfONgYPUgQInGKCrNHuUu33FpiF1d+NlpoEPyxhioEPhBZguJgD3Ycy4poNjqRiXk6e/hZxXWPwXztFlzysTJVERz/GJTnPewPCZOazaZYgxill7El/Co6lujaODmGOEns9fsESbfASUTLy0OuGlIaJg2HkqDD0I7EwZdfjT29JVhVZtqdEBVy4VARYCXlVfoeMvyDOBwWTqZddJ0/UKTSxYSl+Mlp416HIFxoqYd9zNG0WG+J1paTV2Tzt8QoqbkH9i2b7uvKFrNghYOPLnB6gCI3KRiE1fStq1AmsmM7GiY1HUNTL8Fs5jD/zNaXMmvksUrJtKmr3MxUAwdWA6H93aZWJwyGn56sNsdjSO0Dajt+3FDUHVRMxZIi2vxDn3aYpJnMYO/jGBIHqyreO4BWGgIL/PW6CWGlrDVW5RVcTOtECQVJdXG24frovnAFZxx1bRQlV4s6Cyyx9nQVLqqpGVkl84s6epDcrGHjvmAW2jvyMz6sFdVpQhoy7BvqNYopFHilW7G+uuCkb0OEc3Zh/TMbUf9OLJubtetarzsyTAu33pIFsGUHMTaDGNwMZoF80Vqwhlt/u9U/XX86BovZfnf+eCNOD6SxeEFL6N03KI4wbazlGNnHs4=
  file: autodeployapp/build/outputs/apk/autodeployapp*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: tsaisean/AutoDeployExample


before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
